'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace PGI
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PGI.PGITransactionServicesVer2Soap")>  _
    Public Interface PGITransactionServicesVer2Soap
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddAgentTransactionOrder", ReplyAction:="*")>  _
        Function AddAgentTransactionOrder(ByVal request As PGI.AddAgentTransactionOrderRequest) As PGI.AddAgentTransactionOrderResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerifyAgentTransactionPassword", ReplyAction:="*")>  _
        Function VerifyAgentTransactionPassword(ByVal request As PGI.VerifyAgentTransactionPasswordRequest) As PGI.VerifyAgentTransactionPasswordResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddAgentTransactionCancel", ReplyAction:="*")>  _
        Function AddAgentTransactionCancel(ByVal request As PGI.AddAgentTransactionCancelRequest) As PGI.AddAgentTransactionCancelResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddAgentTransactionRefund", ReplyAction:="*")>  _
        Function AddAgentTransactionRefund(ByVal request As PGI.AddAgentTransactionRefundRequest) As PGI.AddAgentTransactionRefundResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAgentTransactionNo", ReplyAction:="*")>  _
        Function GetAgentTransactionNo(ByVal request As PGI.GetAgentTransactionNoRequest) As PGI.GetAgentTransactionNoResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateRemarks", ReplyAction:="*")>  _
        Function UpdateRemarks(ByVal request As PGI.UpdateRemarksRequest) As PGI.UpdateRemarksResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddOrder", ReplyAction:="*")>  _
        Function AddOrder(ByVal request As PGI.AddOrderRequest) As PGI.AddOrderResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddOrderCancel", ReplyAction:="*")>  _
        Function AddOrderCancel(ByVal request As PGI.AddOrderCancelRequest) As PGI.AddOrderCancelResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddOrderRefund", ReplyAction:="*")>  _
        Function AddOrderRefund(ByVal request As PGI.AddOrderRefundRequest) As PGI.AddOrderRefundResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateOrderStatusSuccessFail", ReplyAction:="*")>  _
        Function UpdateOrderStatusSuccessFail(ByVal request As PGI.UpdateOrderStatusSuccessFailRequest) As PGI.UpdateOrderStatusSuccessFailResponse
        
        'CODEGEN: Generating message contract since element name strXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetOrders", ReplyAction:="*")>  _
        Function GetOrders(ByVal request As PGI.GetOrdersRequest) As PGI.GetOrdersResponse
        
        'CODEGEN: Generating message contract since element name strRequestXML from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerifyDiscountCoupon", ReplyAction:="*")>  _
        Function VerifyDiscountCoupon(ByVal request As PGI.VerifyDiscountCouponRequest) As PGI.VerifyDiscountCouponResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddAgentTransactionOrderRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddAgentTransactionOrder", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddAgentTransactionOrderRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddAgentTransactionOrderRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddAgentTransactionOrderRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddAgentTransactionOrderResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddAgentTransactionOrderResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddAgentTransactionOrderResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddAgentTransactionOrderResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddAgentTransactionOrderResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddAgentTransactionOrderResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddAgentTransactionOrderResult As String)
            MyBase.New
            Me.AddAgentTransactionOrderResult = AddAgentTransactionOrderResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerifyAgentTransactionPasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerifyAgentTransactionPassword", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.VerifyAgentTransactionPasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.VerifyAgentTransactionPasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VerifyAgentTransactionPasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerifyAgentTransactionPasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerifyAgentTransactionPasswordResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.VerifyAgentTransactionPasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.VerifyAgentTransactionPasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VerifyAgentTransactionPasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public VerifyAgentTransactionPasswordResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VerifyAgentTransactionPasswordResult As String)
            MyBase.New
            Me.VerifyAgentTransactionPasswordResult = VerifyAgentTransactionPasswordResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddAgentTransactionCancelRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddAgentTransactionCancel", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddAgentTransactionCancelRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddAgentTransactionCancelRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddAgentTransactionCancelRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddAgentTransactionCancelResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddAgentTransactionCancelResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddAgentTransactionCancelResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddAgentTransactionCancelResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddAgentTransactionCancelResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddAgentTransactionCancelResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddAgentTransactionCancelResult As String)
            MyBase.New
            Me.AddAgentTransactionCancelResult = AddAgentTransactionCancelResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddAgentTransactionRefundRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddAgentTransactionRefund", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddAgentTransactionRefundRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddAgentTransactionRefundRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddAgentTransactionRefundRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddAgentTransactionRefundResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddAgentTransactionRefundResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddAgentTransactionRefundResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddAgentTransactionRefundResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddAgentTransactionRefundResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddAgentTransactionRefundResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddAgentTransactionRefundResult As String)
            MyBase.New
            Me.AddAgentTransactionRefundResult = AddAgentTransactionRefundResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAgentTransactionNoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAgentTransactionNo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.GetAgentTransactionNoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.GetAgentTransactionNoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetAgentTransactionNoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAgentTransactionNoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAgentTransactionNoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.GetAgentTransactionNoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.GetAgentTransactionNoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetAgentTransactionNoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetAgentTransactionNoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAgentTransactionNoResult As String)
            MyBase.New
            Me.GetAgentTransactionNoResult = GetAgentTransactionNoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateRemarksRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateRemarks", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.UpdateRemarksRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.UpdateRemarksRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateRemarksRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateRemarksResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateRemarksResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.UpdateRemarksResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.UpdateRemarksResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateRemarksResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpdateRemarksResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateRemarksResult As String)
            MyBase.New
            Me.UpdateRemarksResult = UpdateRemarksResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddOrderRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddOrder", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddOrderRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddOrderRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddOrderRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddOrderResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddOrderResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddOrderResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddOrderResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddOrderResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddOrderResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddOrderResult As String)
            MyBase.New
            Me.AddOrderResult = AddOrderResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddOrderCancelRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddOrderCancel", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddOrderCancelRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddOrderCancelRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddOrderCancelRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddOrderCancelResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddOrderCancelResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddOrderCancelResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddOrderCancelResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddOrderCancelResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddOrderCancelResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddOrderCancelResult As String)
            MyBase.New
            Me.AddOrderCancelResult = AddOrderCancelResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddOrderRefundRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddOrderRefund", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddOrderRefundRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddOrderRefundRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddOrderRefundRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddOrderRefundResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddOrderRefundResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.AddOrderRefundResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.AddOrderRefundResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddOrderRefundResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddOrderRefundResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddOrderRefundResult As String)
            MyBase.New
            Me.AddOrderRefundResult = AddOrderRefundResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateOrderStatusSuccessFailRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateOrderStatusSuccessFail", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.UpdateOrderStatusSuccessFailRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.UpdateOrderStatusSuccessFailRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateOrderStatusSuccessFailRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateOrderStatusSuccessFailResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateOrderStatusSuccessFailResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.UpdateOrderStatusSuccessFailResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.UpdateOrderStatusSuccessFailResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateOrderStatusSuccessFailResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpdateOrderStatusSuccessFailResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateOrderStatusSuccessFailResult As String)
            MyBase.New
            Me.UpdateOrderStatusSuccessFailResult = UpdateOrderStatusSuccessFailResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOrdersRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOrders", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.GetOrdersRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.GetOrdersRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetOrdersRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strXML As String)
            MyBase.New
            Me.strXML = strXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOrdersResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOrdersResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.GetOrdersResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.GetOrdersResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetOrdersResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetOrdersResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetOrdersResult As String)
            MyBase.New
            Me.GetOrdersResult = GetOrdersResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerifyDiscountCouponRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerifyDiscountCoupon", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.VerifyDiscountCouponRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.VerifyDiscountCouponRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VerifyDiscountCouponRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strRequestXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strRequestXML As String)
            MyBase.New
            Me.strRequestXML = strRequestXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerifyDiscountCouponResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerifyDiscountCouponResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PGI.VerifyDiscountCouponResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PGI.VerifyDiscountCouponResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VerifyDiscountCouponResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public VerifyDiscountCouponResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VerifyDiscountCouponResult As String)
            MyBase.New
            Me.VerifyDiscountCouponResult = VerifyDiscountCouponResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PGITransactionServicesVer2SoapChannel
        Inherits PGI.PGITransactionServicesVer2Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PGITransactionServicesVer2SoapClient
        Inherits System.ServiceModel.ClientBase(Of PGI.PGITransactionServicesVer2Soap)
        Implements PGI.PGITransactionServicesVer2Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_AddAgentTransactionOrder(ByVal request As PGI.AddAgentTransactionOrderRequest) As PGI.AddAgentTransactionOrderResponse Implements PGI.PGITransactionServicesVer2Soap.AddAgentTransactionOrder
            Return MyBase.Channel.AddAgentTransactionOrder(request)
        End Function
        
        Public Function AddAgentTransactionOrder(ByVal strXML As String) As String
            Dim inValue As PGI.AddAgentTransactionOrderRequest = New PGI.AddAgentTransactionOrderRequest()
            inValue.Body = New PGI.AddAgentTransactionOrderRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.AddAgentTransactionOrderResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).AddAgentTransactionOrder(inValue)
            Return retVal.Body.AddAgentTransactionOrderResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_VerifyAgentTransactionPassword(ByVal request As PGI.VerifyAgentTransactionPasswordRequest) As PGI.VerifyAgentTransactionPasswordResponse Implements PGI.PGITransactionServicesVer2Soap.VerifyAgentTransactionPassword
            Return MyBase.Channel.VerifyAgentTransactionPassword(request)
        End Function
        
        Public Function VerifyAgentTransactionPassword(ByVal strXML As String) As String
            Dim inValue As PGI.VerifyAgentTransactionPasswordRequest = New PGI.VerifyAgentTransactionPasswordRequest()
            inValue.Body = New PGI.VerifyAgentTransactionPasswordRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.VerifyAgentTransactionPasswordResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).VerifyAgentTransactionPassword(inValue)
            Return retVal.Body.VerifyAgentTransactionPasswordResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_AddAgentTransactionCancel(ByVal request As PGI.AddAgentTransactionCancelRequest) As PGI.AddAgentTransactionCancelResponse Implements PGI.PGITransactionServicesVer2Soap.AddAgentTransactionCancel
            Return MyBase.Channel.AddAgentTransactionCancel(request)
        End Function
        
        Public Function AddAgentTransactionCancel(ByVal strXML As String) As String
            Dim inValue As PGI.AddAgentTransactionCancelRequest = New PGI.AddAgentTransactionCancelRequest()
            inValue.Body = New PGI.AddAgentTransactionCancelRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.AddAgentTransactionCancelResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).AddAgentTransactionCancel(inValue)
            Return retVal.Body.AddAgentTransactionCancelResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_AddAgentTransactionRefund(ByVal request As PGI.AddAgentTransactionRefundRequest) As PGI.AddAgentTransactionRefundResponse Implements PGI.PGITransactionServicesVer2Soap.AddAgentTransactionRefund
            Return MyBase.Channel.AddAgentTransactionRefund(request)
        End Function
        
        Public Function AddAgentTransactionRefund(ByVal strXML As String) As String
            Dim inValue As PGI.AddAgentTransactionRefundRequest = New PGI.AddAgentTransactionRefundRequest()
            inValue.Body = New PGI.AddAgentTransactionRefundRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.AddAgentTransactionRefundResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).AddAgentTransactionRefund(inValue)
            Return retVal.Body.AddAgentTransactionRefundResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_GetAgentTransactionNo(ByVal request As PGI.GetAgentTransactionNoRequest) As PGI.GetAgentTransactionNoResponse Implements PGI.PGITransactionServicesVer2Soap.GetAgentTransactionNo
            Return MyBase.Channel.GetAgentTransactionNo(request)
        End Function
        
        Public Function GetAgentTransactionNo(ByVal strXML As String) As String
            Dim inValue As PGI.GetAgentTransactionNoRequest = New PGI.GetAgentTransactionNoRequest()
            inValue.Body = New PGI.GetAgentTransactionNoRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.GetAgentTransactionNoResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).GetAgentTransactionNo(inValue)
            Return retVal.Body.GetAgentTransactionNoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_UpdateRemarks(ByVal request As PGI.UpdateRemarksRequest) As PGI.UpdateRemarksResponse Implements PGI.PGITransactionServicesVer2Soap.UpdateRemarks
            Return MyBase.Channel.UpdateRemarks(request)
        End Function
        
        Public Function UpdateRemarks(ByVal strXML As String) As String
            Dim inValue As PGI.UpdateRemarksRequest = New PGI.UpdateRemarksRequest()
            inValue.Body = New PGI.UpdateRemarksRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.UpdateRemarksResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).UpdateRemarks(inValue)
            Return retVal.Body.UpdateRemarksResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_AddOrder(ByVal request As PGI.AddOrderRequest) As PGI.AddOrderResponse Implements PGI.PGITransactionServicesVer2Soap.AddOrder
            Return MyBase.Channel.AddOrder(request)
        End Function
        
        Public Function AddOrder(ByVal strXML As String) As String
            Dim inValue As PGI.AddOrderRequest = New PGI.AddOrderRequest()
            inValue.Body = New PGI.AddOrderRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.AddOrderResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).AddOrder(inValue)
            Return retVal.Body.AddOrderResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_AddOrderCancel(ByVal request As PGI.AddOrderCancelRequest) As PGI.AddOrderCancelResponse Implements PGI.PGITransactionServicesVer2Soap.AddOrderCancel
            Return MyBase.Channel.AddOrderCancel(request)
        End Function
        
        Public Function AddOrderCancel(ByVal strXML As String) As String
            Dim inValue As PGI.AddOrderCancelRequest = New PGI.AddOrderCancelRequest()
            inValue.Body = New PGI.AddOrderCancelRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.AddOrderCancelResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).AddOrderCancel(inValue)
            Return retVal.Body.AddOrderCancelResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_AddOrderRefund(ByVal request As PGI.AddOrderRefundRequest) As PGI.AddOrderRefundResponse Implements PGI.PGITransactionServicesVer2Soap.AddOrderRefund
            Return MyBase.Channel.AddOrderRefund(request)
        End Function
        
        Public Function AddOrderRefund(ByVal strXML As String) As String
            Dim inValue As PGI.AddOrderRefundRequest = New PGI.AddOrderRefundRequest()
            inValue.Body = New PGI.AddOrderRefundRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.AddOrderRefundResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).AddOrderRefund(inValue)
            Return retVal.Body.AddOrderRefundResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_UpdateOrderStatusSuccessFail(ByVal request As PGI.UpdateOrderStatusSuccessFailRequest) As PGI.UpdateOrderStatusSuccessFailResponse Implements PGI.PGITransactionServicesVer2Soap.UpdateOrderStatusSuccessFail
            Return MyBase.Channel.UpdateOrderStatusSuccessFail(request)
        End Function
        
        Public Function UpdateOrderStatusSuccessFail(ByVal strXML As String) As String
            Dim inValue As PGI.UpdateOrderStatusSuccessFailRequest = New PGI.UpdateOrderStatusSuccessFailRequest()
            inValue.Body = New PGI.UpdateOrderStatusSuccessFailRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.UpdateOrderStatusSuccessFailResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).UpdateOrderStatusSuccessFail(inValue)
            Return retVal.Body.UpdateOrderStatusSuccessFailResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_GetOrders(ByVal request As PGI.GetOrdersRequest) As PGI.GetOrdersResponse Implements PGI.PGITransactionServicesVer2Soap.GetOrders
            Return MyBase.Channel.GetOrders(request)
        End Function
        
        Public Function GetOrders(ByVal strXML As String) As String
            Dim inValue As PGI.GetOrdersRequest = New PGI.GetOrdersRequest()
            inValue.Body = New PGI.GetOrdersRequestBody()
            inValue.Body.strXML = strXML
            Dim retVal As PGI.GetOrdersResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).GetOrders(inValue)
            Return retVal.Body.GetOrdersResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PGI_PGITransactionServicesVer2Soap_VerifyDiscountCoupon(ByVal request As PGI.VerifyDiscountCouponRequest) As PGI.VerifyDiscountCouponResponse Implements PGI.PGITransactionServicesVer2Soap.VerifyDiscountCoupon
            Return MyBase.Channel.VerifyDiscountCoupon(request)
        End Function
        
        Public Function VerifyDiscountCoupon(ByVal strRequestXML As String) As String
            Dim inValue As PGI.VerifyDiscountCouponRequest = New PGI.VerifyDiscountCouponRequest()
            inValue.Body = New PGI.VerifyDiscountCouponRequestBody()
            inValue.Body.strRequestXML = strRequestXML
            Dim retVal As PGI.VerifyDiscountCouponResponse = CType(Me,PGI.PGITransactionServicesVer2Soap).VerifyDiscountCoupon(inValue)
            Return retVal.Body.VerifyDiscountCouponResult
        End Function
    End Class
End Namespace
